### ISSUE TITLE
The dosage looks wrong

### ISSUE THREAD

**Issue by ew0855** [nhshackday/mobileformulary#1] opened 2012-05-27 15:20 UTC
Not sure what you are scraping for the dose but its not the same as the BNF site, try searching for paracetamol as an example, 

BNF.org says "By Mouth 0.5-1g Every 4 hours, max 4g daily...."

Your app says: " Migraine, 2 capsules at onset of attack, followed by 1 capsule every hour if necessary; max. 5 capsules in 12 hours;childnot recommended"

**Comment by davidmiller** [comment] 2012-06-12 17:51
This is essentially a duplicate of #2 
As you say It's a slightly subtle scraping thing.

**Comment by davidmiller** [comment] 2012-08-04 16:13
This was addressed in 62bf426a179218f080f205097a3e53de4b82ec2b 19b72842ca38071043e62c682c448369052f673c 1f82666f07e7c3a97a86c9accb5af3f793935227

These changes have been deployed to OpenBNF.org

**Closed as completed by davidmiller** 2012-08-04 16:13 UTC
